refactored to new driver script method with less statement duplication

diff --git a/environment/bin/environment-delete-vpc-stack b/environment/bin/environment-delete-vpc-stack
--- a/environment/bin/environment-delete-vpc-stack
+++ b/environment/bin/environment-delete-vpc-stack
@@ -28,6 +28,7 @@ delete_attempts=20
 interactive=1
 speed=100
 verbose=0
+environment=${ENVIRONMENT_NAME:-Production}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -37,14 +38,16 @@ user=${AWS_USER_NAME:-administrator}
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "              [-r region ] [-a account] [-u user]"
-    echo "  -I          non-interactive"
-    echo "  -s          slower: increase pauses by 25%"
-    echo "  -f          faster: reduce pauses by 25%"
-    echo "  -v          verbose"
-    echo "  -r region   Region (default: $region)"
-    echo "  -a account  Account (default: $account)"
-    echo "  -u user     User (default: $user)"
+    echo "                  [-E environment]"
+    echo "                  [-r region ] [-a account] [-u user]"
+    echo "  -I              non-interactive"
+    echo "  -s              slower: increase pauses by 25%"
+    echo "  -f              faster: reduce pauses by 25%"
+    echo "  -v              verbose"
+    echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -r region       Region (default: $region)"
+    echo "  -a account      Account (default: $account)"
+    echo "  -u user         User (default: $user)"
 }
 
 run() {
@@ -127,12 +130,13 @@ next() {
 
 #  3. Parse command line options
 
-while getopts Isfvr:a:u:? arg; do
+while getopts IsfvE:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    E)  environment="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -146,10 +150,16 @@ shift $(($OPTIND - 1))
 
 #  4. Validate environment
 
+if [ -z $environment ]; then
+    echo "-E environment missing!"
+    echo "Could not automatically determine environment, and it was not specified as a parameter"
+    exit 16
+fi
+
 if [ -z $region ]; then
     echo "-r region missing!"
     echo "Could not automatically determine region, and it was not specified as a parameter"
-    exit 20
+    exit 50
 else
     case $region in
       us-east-1)
@@ -158,34 +168,34 @@ else
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
-        exit 21;;
+        exit 51;;
     esac
 fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
     echo "Could not automatically determine account, and it was not specified as a parameter"
-    exit 22
+    exit 52
 fi
 
 if [ -z $user ]; then
     echo "-u user missing!"
     echo "Could not automatically determine user, and it was not specified as a parameter"
-    exit 24
+    exit 54
 fi
 
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
-    echo "Could not find AWS ($account) Account Demo ($user) User AWSCLI profile!"
+    echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 53
+    exit 60
 fi
 
-if ! aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \
+if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - $ENVIRONMENT_NAME-VPC Stack does not exist!"
-    exit 2
+    echo "Unable to delete - $environment-VPC Stack does not exist!"
+    exit 70
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -200,6 +210,13 @@ unset EC2_CERT
 start=$(date +%s)
 
 ((++step))
+read -r -d '' statement << EOS
+aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
+                                   --profile $profile --region $region --output table
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'}"
+
 if [ $verbose = 1 ]; then
     clear
     echo
@@ -211,18 +228,14 @@ if [ $verbose = 1 ]; then
     echo
     echo "Commands:"
     echo
-    echo "aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\"
-    echo "                                   --profile $profile --region $region --output table"
-
+    echo "$statement"
 
     run 50
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\"
-        echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \
-                                           --profile $profile --region $region --output table
+        echo "$run_statement"
+        eval "$eval_statement"
 
         next
     fi
@@ -230,6 +243,14 @@ fi
 
 
 ((++step))
+read -r -d '' statement << EOS
+aws cloudformation delete-stack --stack-name $environment-VPC \\
+                                --profile $profile --region $region --output table
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'} 2> /dev/null"
+
+
 clear
 echo
 echo "============================================================"
@@ -240,11 +261,10 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation delete-stack --stack-name $ENVIRONMENT_NAME-VPC \\"
-echo "                                --profile $profile --region $region --output table"
+echo "$statement"
 
-if ! aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \
-                                      --profile $profile --region $region --output text &> /dev/null; then
+if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
+                                        --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
     echo "Already Deleted!"
@@ -257,10 +277,8 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation delete-stack --stack-name $ENVIRONMENT_NAME-VPC \\"
-        echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation delete-stack --stack-name $ENVIRONMENT_NAME-VPC \
-                                        --profile $profile --region $region --output table
+        echo "$run_statement"
+        eval "$eval_statement"
 
         next
     fi
@@ -268,6 +286,22 @@ fi
 
 
 ((++step))
+read -r -d '' statement << EOS
+aws cloudformation describe-stacks --stack-name $environment-VPC \\
+                                   --query 'Stacks[].[StackName,StackStatus]' \\
+                                   --profile $profile --region $region --output table
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'} 2> /dev/null"
+
+read -r -d '' statement2 << EOS
+aws cloudformation describe-stack-events --stack-name $environment-VPC --max-items 5 \\
+                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
+                                         --profile $profile --region $region --output table
+EOS
+run_statement2=$(echo "$statement2" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement2="${statement2//\\$'\n'} 2> /dev/null"
+
 clear
 echo
 echo "============================================================"
@@ -278,15 +312,11 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \\"
-echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
-echo "                                   --profile $profile --region $region --output table"
+echo "$statement"
 echo
-echo "aws cloudformation describe-stack-events --stack-name $ENVIRONMENT_NAME-VPC --max-items 5 \\"
-echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
-echo "                                         --profile $profile --region $region --output table"
+echo "$statement2"
 
-if ! aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \
+if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region &> /dev/null; then
     echo
     tput rev
@@ -300,34 +330,24 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \\"
-        echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
-        echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \
-                                           --query 'Stacks[].[StackName,StackStatus]' \
-                                           --profile $profile --region $region --output table 2> /dev/null
-        pause
+        echo "$run_statement"
+        eval "$eval_statement"
 
         attempt=0
         seconds=$delete_default
         while ((attempt++ <= delete_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name $ENVIRONMENT_NAME-VPC --max-items 5 \\"
-            echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
-            echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name $ENVIRONMENT_NAME-VPC --max-items 5 \
-                                                     --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
-                                                     --profile $profile --region $region --output table 2> /dev/null
+            echo "$run_statement2"
+            eval "$eval_statement2"
 
-            status=$(aws cloudformation describe-stacks --stack-name $ENVIRONMENT_NAME-VPC \
+            status=$(aws cloudformation describe-stacks --stack-name $environment-VPC \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            RC=$?
             if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
-                echo -n "Not finished ($RC). Waiting $seconds seconds..."
+                echo -n "Not finished ($status). Waiting $seconds seconds..."
                 sleep $seconds
                 echo " Done"
             fi
@@ -339,6 +359,13 @@ fi
 
 
 ((++step))
+read -r -d '' statement << EOS
+aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
+                                   --profile $profile --region $region --output table
+EOS
+run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
+eval_statement="${statement//\\$'\n'}"
+
 if [ $verbose = 1 ]; then
     clear
     echo
@@ -350,19 +377,14 @@ if [ $verbose = 1 ]; then
     echo
     echo "Commands:"
     echo
-    echo "aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\"
-    echo "                                   --profile $profile --region $region --output table"
-    echo
-
+    echo "$statement"
 
     run 50
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\"
-        echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \
-                                           --profile $profile --region $region --output table
+        echo "$run_statement"
+        eval "$eval_statement"
 
         next
     fi
