updated all drivers to pass new parameters

diff --git a/environment/bin/environment-update-all-stacks b/environment/bin/environment-update-all-stacks
--- a/environment/bin/environment-update-all-stacks
+++ b/environment/bin/environment-update-all-stacks
@@ -28,6 +28,12 @@ create_attempts=20
 interactive=1
 speed=100
 verbose=0
+owner=${OWNER_EMAIL:-$USER@hpe.com}
+company=${COMPANY_NAME:-Demo}
+system=${SYSTEM_NAME:-IROPS}
+environment=${ENVIRONMENT_NAME:-Production}
+environment_domain=${ENVIRONMENT_DOMAIN:-demo.iropshub.com}
+environment_network=${ENVIRONMENT_NETWORK:-10.40.0.0/16}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-irops}
 user=${AWS_USER_NAME:-administrator}
@@ -37,14 +43,22 @@ user=${AWS_USER_NAME:-administrator}
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "              [-r region ] [-a account] [-u user]"
-    echo "  -I          non-interactive"
-    echo "  -s          slower: increase pauses by 25%"
-    echo "  -f          faster: reduce pauses by 25%"
-    echo "  -v          verbose"
-    echo "  -r region   Region (default: $region)"
-    echo "  -a account  Account (default: $account)"
-    echo "  -u user     User (default: $user)"
+    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-E environment] [-D domain] [-N network ]"
+    echo "                  [-r region ] [-a account] [-u user]"
+    echo "  -I              non-interactive"
+    echo "  -s              slower: increase pauses by 25%"
+    echo "  -f              faster: reduce pauses by 25%"
+    echo "  -v              verbose"
+    echo "  -O owner        Owner Email (default: $owner)"
+    echo "  -C company      Company Name (default: $company)"
+    echo "  -S system       System Name (default: $system)"
+    echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -D domain       Environment Domain (default: $environment_domain)"
+    echo "  -N network      Environment Network (default: $environment_network)"
+    echo "  -r region       Region (default: $region)"
+    echo "  -a account      Account (default: $account)"
+    echo "  -u user         User (default: $user)"
 }
 
 run() {
@@ -128,12 +142,18 @@ next() {
 #  3. Parse command line options
 
 unset options
-while getopts Isfvr:a:u:? arg; do
+while getopts IsfvO:C:S:E:D:N:r:a:u:? arg; do
     case $arg in
     I)  interactive=0; options="$options -I";;
     s)  ((speed < speed_max)) && ((speed=speed+25)); options="$options -s";;
     f)  ((speed > 0)) && ((speed=speed-25)); options="$options -f";;
     v)  verbose=1; options="$options -v";;
+    O)  owner="$OPTARG"; options="$options -O $OPTARG";;
+    C)  company="$OPTARG"; options="$options -C $OPTARG";;
+    S)  system="$OPTARG"; options="$options -S $OPTARG";;
+    E)  environment="$OPTARG"; options="$options -E $OPTARG";;
+    D)  environment_domain="$OPTARG"; options="$options -D $OPTARG";;
+    N)  environment_network="$OPTARG"; options="$options -N $OPTARG";;
     r)  region="$OPTARG"; options="$options -r $OPTARG";;
     a)  account="$OPTARG"; options="$options -a $OPTARG";;
     u)  user="$OPTARG"; options="$options -u $OPTARG";;
@@ -148,10 +168,46 @@ shift $(($OPTIND - 1))
 
 #  4. Validate environment
 
+if [ -z $owner ]; then
+    echo "-O owner missing!"
+    echo "Could not automatically determine owner, and it was not specified as a parameter"
+    exit 10
+fi
+
+if [ -z $company ]; then
+    echo "-C company missing!"
+    echo "Could not automatically determine company, and it was not specified as a parameter"
+    exit 12
+fi
+
+if [ -z $system ]; then
+    echo "-S system missing!"
+    echo "Could not automatically determine system, and it was not specified as a parameter"
+    exit 14
+fi
+
+if [ -z $environment ]; then
+    echo "-E environment missing!"
+    echo "Could not automatically determine environment, and it was not specified as a parameter"
+    exit 16
+fi
+
+if [ -z $environment_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine environmeht domain, and it was not specified as a parameter"
+    exit 18
+fi
+
+if [ -z $environment_network ]; then
+    echo "-N network missing!"
+    echo "Could not automatically determine environment network, and it was not specified as a parameter"
+    exit 20
+fi
+
 if [ -z $region ]; then
     echo "-r region missing!"
     echo "Could not automatically determine region, and it was not specified as a parameter"
-    exit 20
+    exit 50
 else
     case $region in
       us-east-1)
@@ -160,20 +216,20 @@ else
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
-        exit 21;;
+        exit 51;;
     esac
 fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
     echo "Could not automatically determine account, and it was not specified as a parameter"
-    exit 22
+    exit 52
 fi
 
 if [ -z $user ]; then
     echo "-u user missing!"
     echo "Could not automatically determine user, and it was not specified as a parameter"
-    exit 24
+    exit 54
 fi
 
 profile=$account-$user
@@ -181,7 +237,7 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 53
+    exit 60
 fi
 
 # Prevent certain environment variables from breaking commands
