refactor file naming convention slightly to remove Service; add more topics; split out custom subscriptions

diff --git a/core/bin/core-create-standardtopics-stack b/core/bin/core-create-standardtopics-stack
--- a/core/bin/core-create-standardtopics-stack
+++ b/core/bin/core-create-standardtopics-stack
@@ -1,9 +1,15 @@
 #!/bin/bash
 #
-# This script deletes the S3 StandardBuckets Stack in the Core Account.
+# This script creates the StandardTopics Stack in the Core Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
+#
+# Since this script is run during initial bootstrapping of an Account which 
+# may not yet have certain S3 buckets created to hold templates, the
+# script checks for the existance of the S3 templates bucket, and if it 
+# exists, it will upload the template to the bucket and run it via URL,
+# but if it does not exist, it will run it via file.
 #
 
 #  1. Initalize Environment
@@ -22,8 +28,8 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-delete_default=15
-delete_attempts=20
+create_default=15
+create_attempts=20
 
 interactive=1
 speed=100
@@ -31,6 +37,9 @@ verbose=0
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_NAME:-irops}
 user=${AWS_USER_NAME:-administrator}
+
+templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$account}
+templatespath=/core
 
 
 #  2. Define functions
@@ -177,15 +186,13 @@ fi
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
-    echo "Could not find AWS ($account) Account Demo ($user) User AWSCLI profile!"
+    echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
     exit 53
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardBuckets \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - StandardBuckets Stack does not exist!"
-    exit 2
+if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
+    unset templatesbucket
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -198,6 +205,7 @@ unset EC2_CERT
 #  5. Run
 
 start=$(date +%s)
+
 
 ((++step))
 if [ $verbose = 1 ]; then
@@ -230,24 +238,69 @@ fi
 
 
 ((++step))
+if [ -n $templatesbucket ]; then
+    clear
+    echo
+    echo "============================================================"
+    echo
+    echo "$(printf '%2d' $step). Sync Template to ($templatesbucket) Bucket"
+    echo
+    echo "============================================================"
+    echo
+    echo "Commands:"
+    echo
+    echo "aws s3 sync $templatesdir \\"
+    echo "            s3://$templatesbucket$templatespath \\"
+    echo "            --exclude '*' --include 'Core-StandardTopics.json' \\"
+    echo "            --profile $profile --region $region --output table"
+
+    next 50
+
+    echo
+    echo "# aws s3 sync $templatesdir \\"
+    echo ">             s3://$templatesbucket$templatespath \\"
+    echo ">             --exclude '*' --include 'Core-StandardTopics.json' \\"
+    echo ">             --profile $profile --region $region --output table"
+    aws s3 sync $templatesdir \
+                s3://$templatesbucket$templatespath \
+                --exclude '*' --include 'Core-StandardTopics.json' \
+                --profile $profile --region $region --output table
+
+    next 50
+fi
+
+
+((++step))
 clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Delete the Stack"
+echo "$(printf '%2d' $step). Create the Stack"
+if [ -n $templatesbucket ]; then
+    echo "    - Referencing the template as an S3 URL"
+else
+    echo "    - Referencing the template as a local File"
+fi
 echo
 echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation delete-stack --stack-name StandardBuckets \\"
-echo "                                --profile $profile --region $region --output table"
+if [ -n $templatesbucket ]; then
+    echo "aws cloudformation create-stack --stack-name StandardTopics \\"
+    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Core-StandardTopics.json \\"
+    echo "                                --profile $profile --region $region --output table"
+else
+    echo "aws cloudformation create-stack --stack-name StandardTopics \\"
+    echo "                                --template-body file://$templatesdir/Core-StandardTopics.json \\"
+    echo "                                --profile $profile --region $region --output table"
+fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardBuckets \
+if aws cloudformation describe-stacks --stack-name StandardTopics \
                                       --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
-    echo "Already Deleted!"
+    echo "Already Created!"
     tput sgr0
 
     next 50
@@ -257,10 +310,21 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation delete-stack --stack-name StandardBuckets \\"
-        echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation delete-stack --stack-name StandardBuckets \
-                                        --profile $profile --region $region --output table
+        if [ -n $templates-bucket ]; then
+            echo "# aws cloudformation create-stack --stack-name StandardTopics \\"
+            echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Core-StandardTopics.json \\"
+            echo ">                                 --profile $profile --region $region --output table"
+            aws cloudformation create-stack --stack-name StandardTopics \
+                                            --template-url https://$s3_domain/$templatesbucket$templatespath/Core-StandardTopics.json \
+                                            --profile $profile --region $region --output table
+        else
+            echo "# aws cloudformation create-stack --stack-name StandardTopics \\"
+            echo ">                                 --template-body file://$templatesdir/Core-StandardTopics.json \\"
+            echo ">                                 --profile $profile --region $region --output table"
+            aws cloudformation create-stack --stack-name StandardTopics \
+                                            --template-body file://$templatesdir/Core-StandardTopics.json \
+                                            --profile $profile --region $region --output table
+        fi
 
         next
     fi
@@ -272,25 +336,26 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack deletion"
+echo "$(printf '%2d' $step). Monitor Stack creation"
 echo
 echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name StandardBuckets \\"
+echo "aws cloudformation describe-stacks --stack-name StandardTopics \\"
 echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
 echo "                                   --profile $profile --region $region --output table"
 echo
-echo "aws cloudformation describe-stack-events --stack-name StandardBuckets --max-items 5 \\"
+echo "aws cloudformation describe-stack-events --stack-name StandardTopics --max-items 5 \\"
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if ! aws cloudformation describe-stacks --stack-name StandardBuckets \
-                                        --profile $profile --region $region &> /dev/null; then
+if [ "$(aws cloudformation describe-stacks --stack-name StandardTopics \
+                                           --query 'Stacks[].StackStatus' \
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
     echo
     tput rev
-    echo "Already Deleted!"
+    echo "Already Complete!"
     tput sgr0
 
     next 50
@@ -300,26 +365,26 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name StandardBuckets \\"
+        echo "# aws cloudformation describe-stacks --stack-name StandardTopics \\"
         echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
         echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name StandardBuckets \
+        aws cloudformation describe-stacks --stack-name StandardTopics \
                                            --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table 2> /dev/null
         pause
 
         attempt=0
-        seconds=$delete_default
-        while ((attempt++ <= delete_attempts)); do
+        seconds=$create_default
+        while ((attempt++ <= create_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name StandardBuckets --max-items 5 \\"
+            echo "# aws cloudformation describe-stack-events --stack-name StandardTopics --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
             echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name StandardBuckets --max-items 5 \
+            aws cloudformation describe-stack-events --stack-name StandardTopics --max-items 5 \
                                                      --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
                                                      --profile $profile --region $region --output table 2> /dev/null
 
-            status=$(aws cloudformation describe-stacks --stack-name StandardBuckets \
+            status=$(aws cloudformation describe-stacks --stack-name StandardTopics \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -362,6 +427,38 @@ if [ $verbose = 1 ]; then
         echo ">                                    --profile $profile --region $region --output table"
         aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table
+
+        next
+    fi
+fi
+
+
+((++step))
+if [ $verbose = 1 ]; then
+    clear
+    echo
+    echo "============================================================"
+    echo
+    echo "$(printf '%2d' $step). List Resulting Stack Resources"
+    echo
+    echo "============================================================"
+    echo
+    echo "Commands:"
+    echo
+    echo "aws cloudformation describe-stack-resources --stack-name StandardTopics \\"
+    echo "                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
+    echo "                                            --profile $profile --region $region --output table"
+
+    run 50
+
+    if [ $choice = y ]; then
+        echo
+        echo "# aws cloudformation describe-stack-resources --stack-name StandardTopics \\"
+        echo ">                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
+        echo ">                                             --profile $profile --region $region --output table"
+        aws cloudformation describe-stack-resources --stack-name StandardTopics \
+                                                    --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \
+                                                    --profile $profile --region $region --output table 2> /dev/null
 
         next
     fi
diff --git a/core/bin/core-update-customsubscriptions-stack b/core/bin/core-update-customsubscriptions-stack
--- a/core/bin/core-update-customsubscriptions-stack
+++ b/core/bin/core-update-customsubscriptions-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the SNS StandardSubscriptions Stack in the Core Account.
+# This script updates the CustomSubscriptions Stack in the Core Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -195,9 +195,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardSubscriptions \
+if ! aws cloudformation describe-stacks --stack-name CustomSubscriptions \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - StandardSubscriptions Stack does not exist!"
+    echo "Unable to update - CustomSubscriptions Stack does not exist!"
     exit 2
 fi
 
@@ -257,7 +257,7 @@ if [ -n $templatesbucket ]; then
     echo
     echo "aws s3 sync $templatesdir \\"
     echo "            s3://$templatesbucket$templatespath \\"
-    echo "            --exclude '*' --include 'Core-SNS-StandardSubscriptions.json' \\"
+    echo "            --exclude '*' --include 'Core-CustomSubscriptions.json' \\"
     echo "            --profile $profile --region $region --output table"
 
     next 50
@@ -265,11 +265,11 @@ if [ -n $templatesbucket ]; then
     echo
     echo "# aws s3 sync $templatesdir \\"
     echo ">             s3://$templatesbucket$templatespath \\"
-    echo ">             --exclude '*' --include 'Core-SNS-StandardSubscriptions.json' \\"
+    echo ">             --exclude '*' --include 'Core-CustomSubscriptions.json' \\"
     echo ">             --profile $profile --region $region --output table"
     aws s3 sync $templatesdir \
                 s3://$templatesbucket$templatespath \
-                --exclude '*' --include 'Core-SNS-StandardSubscriptions.json' \
+                --exclude '*' --include 'Core-CustomSubscriptions.json' \
                 --profile $profile --region $region --output table
 
     next 50
@@ -293,12 +293,12 @@ echo
 echo "Commands:"
 echo
 if [ -n $templatesbucket ]; then
-    echo "aws cloudformation update-stack --stack-name StandardSubscriptions \\"
-    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Core-SNS-StandardSubscriptions.json \\"
+    echo "aws cloudformation update-stack --stack-name CustomSubscriptions \\"
+    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Core-CustomSubscriptions.json \\"
     echo "                                --profile $profile --region $region --output table"
 else
-    echo "aws cloudformation update-stack --stack-name StandardSubscriptions \\"
-    echo "                                --template-body file://$templatesdir/Core-SNS-StandardSubscriptions.json \\"
+    echo "aws cloudformation update-stack --stack-name CustomSubscriptions \\"
+    echo "                                --template-body file://$templatesdir/Core-CustomSubscriptions.json \\"
     echo "                                --profile $profile --region $region --output table"
 fi
 
@@ -307,18 +307,18 @@ run
 if [ $choice = y ]; then
     echo
     if [ -n $templates-bucket ]; then
-        echo "# aws cloudformation update-stack --stack-name StandardSubscriptions \\"
-        echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Core-SNS-StandardSubscriptions.json \\"
+        echo "# aws cloudformation update-stack --stack-name CustomSubscriptions \\"
+        echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Core-CustomSubscriptions.json \\"
         echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation update-stack --stack-name StandardSubscriptions \
-                                        --template-url https://$s3_domain/$templatesbucket$templatespath/Core-SNS-StandardSubscriptions.json \
+        aws cloudformation update-stack --stack-name CustomSubscriptions \
+                                        --template-url https://$s3_domain/$templatesbucket$templatespath/Core-CustomSubscriptions.json \
                                         --profile $profile --region $region --output table
     else
-        echo "# aws cloudformation update-stack --stack-name StandardSubscriptions \\"
-        echo ">                                 --template-body file://$templatesdir/Core-SNS-StandardSubscriptions.json \\"
+        echo "# aws cloudformation update-stack --stack-name CustomSubscriptions \\"
+        echo ">                                 --template-body file://$templatesdir/Core-CustomSubscriptions.json \\"
         echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation update-stack --stack-name StandardSubscriptions \
-                                        --template-body file://$templatesdir/Core-SNS-StandardSubscriptions.json \
+        aws cloudformation update-stack --stack-name CustomSubscriptions \
+                                        --template-body file://$templatesdir/Core-CustomSubscriptions.json \
                                         --profile $profile --region $region --output table
     fi
 
@@ -337,15 +337,15 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name StandardSubscriptions \\"
+echo "aws cloudformation describe-stacks --stack-name CustomSubscriptions \\"
 echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
 echo "                                   --profile $profile --region $region --output table"
 echo
-echo "aws cloudformation describe-stack-events --stack-name StandardSubscriptions --max-items 5 \\"
+echo "aws cloudformation describe-stack-events --stack-name CustomSubscriptions --max-items 5 \\"
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if [ "$(aws cloudformation describe-stacks --stack-name StandardSubscriptions \
+if [ "$(aws cloudformation describe-stacks --stack-name CustomSubscriptions \
                                            --query 'Stacks[].StackStatus' \
                                            --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
@@ -360,10 +360,10 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name StandardSubscriptions \\"
+        echo "# aws cloudformation describe-stacks --stack-name CustomSubscriptions \\"
         echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
         echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name StandardSubscriptions \
+        aws cloudformation describe-stacks --stack-name CustomSubscriptions \
                                            --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table 2> /dev/null
         pause
@@ -372,14 +372,14 @@ else
         seconds=$update_default
         while ((attempt++ <= update_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name StandardSubscriptions --max-items 5 \\"
+            echo "# aws cloudformation describe-stack-events --stack-name CustomSubscriptions --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
             echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name StandardSubscriptions --max-items 5 \
+            aws cloudformation describe-stack-events --stack-name CustomSubscriptions --max-items 5 \
                                                      --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
                                                      --profile $profile --region $region --output table 2> /dev/null
 
-            status=$(aws cloudformation describe-stacks --stack-name StandardSubscriptions \
+            status=$(aws cloudformation describe-stacks --stack-name CustomSubscriptions \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -440,7 +440,7 @@ if [ $verbose = 1 ]; then
     echo
     echo "Commands:"
     echo
-    echo "aws cloudformation describe-stack-resources --stack-name StandardSubscriptions \\"
+    echo "aws cloudformation describe-stack-resources --stack-name CustomSubscriptions \\"
     echo "                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
     echo "                                            --profile $profile --region $region --output table"
 
@@ -448,10 +448,10 @@ if [ $verbose = 1 ]; then
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stack-resources --stack-name StandardSubscriptions \\"
+        echo "# aws cloudformation describe-stack-resources --stack-name CustomSubscriptions \\"
         echo ">                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
         echo ">                                             --profile $profile --region $region --output table"
-        aws cloudformation describe-stack-resources --stack-name StandardSubscriptions \
+        aws cloudformation describe-stack-resources --stack-name CustomSubscriptions \
                                                     --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \
                                                     --profile $profile --region $region --output table 2> /dev/null
 
diff --git a/core/bin/core-update-standardsubscriptions-stack b/core/bin/core-update-standardsubscriptions-stack
--- a/core/bin/core-update-standardsubscriptions-stack
+++ b/core/bin/core-update-standardsubscriptions-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script updates the S3 StandardBuckets Stack in the Core Account.
+# This script updates the StandardSubscriptions Stack in the Core Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -195,9 +195,9 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardBuckets \
+if ! aws cloudformation describe-stacks --stack-name StandardSubscriptions \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - StandardBuckets Stack does not exist!"
+    echo "Unable to update - StandardSubscriptions Stack does not exist!"
     exit 2
 fi
 
@@ -244,7 +244,7 @@ fi
 
 
 ((++step))
-if [ ! -z $templatesbucket ]; then
+if [ -n $templatesbucket ]; then
     clear
     echo
     echo "============================================================"
@@ -257,7 +257,7 @@ if [ ! -z $templatesbucket ]; then
     echo
     echo "aws s3 sync $templatesdir \\"
     echo "            s3://$templatesbucket$templatespath \\"
-    echo "            --exclude '*' --include 'Core-S3-StandardBuckets.json' \\"
+    echo "            --exclude '*' --include 'Core-StandardSubscriptions.json' \\"
     echo "            --profile $profile --region $region --output table"
 
     next 50
@@ -265,11 +265,11 @@ if [ ! -z $templatesbucket ]; then
     echo
     echo "# aws s3 sync $templatesdir \\"
     echo ">             s3://$templatesbucket$templatespath \\"
-    echo ">             --exclude '*' --include 'Core-S3-StandardBuckets.json' \\"
+    echo ">             --exclude '*' --include 'Core-StandardSubscriptions.json' \\"
     echo ">             --profile $profile --region $region --output table"
     aws s3 sync $templatesdir \
                 s3://$templatesbucket$templatespath \
-                --exclude '*' --include 'Core-S3-StandardBuckets.json' \
+                --exclude '*' --include 'Core-StandardSubscriptions.json' \
                 --profile $profile --region $region --output table
 
     next 50
@@ -282,7 +282,7 @@ echo
 echo "============================================================"
 echo
 echo "$(printf '%2d' $step). Update the Stack"
-if [ ! -z $templatesbucket ]; then
+if [ -n $templatesbucket ]; then
     echo "    - Referencing the template as an S3 URL"
 else
     echo "    - Referencing the template as a local File"
@@ -292,15 +292,13 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-if [ ! -z $templatesbucket ]; then
-    echo "aws cloudformation update-stack --stack-name StandardBuckets \\"
-    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Core-S3-StandardBuckets.json \\"
-    echo "                                --parameters ParameterKey=AccountAlias,ParameterValue=$AWS_ACCOUNT_NAME \\"
+if [ -n $templatesbucket ]; then
+    echo "aws cloudformation update-stack --stack-name StandardSubscriptions \\"
+    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Core-StandardSubscriptions.json \\"
     echo "                                --profile $profile --region $region --output table"
 else
-    echo "aws cloudformation update-stack --stack-name StandardBuckets \\"
-    echo "                                --template-body file://$templatesdir/Core-S3-StandardBuckets.json \\"
-    echo "                                --parameters ParameterKey=AccountAlias,ParameterValue=$AWS_ACCOUNT_NAME \\"
+    echo "aws cloudformation update-stack --stack-name StandardSubscriptions \\"
+    echo "                                --template-body file://$templatesdir/Core-StandardSubscriptions.json \\"
     echo "                                --profile $profile --region $region --output table"
 fi
 
@@ -308,23 +306,19 @@ run
 
 if [ $choice = y ]; then
     echo
-    if [ ! -z $templatesbucket ]; then
-        echo "# aws cloudformation update-stack --stack-name StandardBuckets \\"
-        echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Core-S3-StandardBuckets.json \\"
-        echo ">                                 --parameters ParameterKey=AccountAlias,ParameterValue=$AWS_ACCOUNT_NAME \\"
+    if [ -n $templates-bucket ]; then
+        echo "# aws cloudformation update-stack --stack-name StandardSubscriptions \\"
+        echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Core-StandardSubscriptions.json \\"
         echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation update-stack --stack-name StandardBuckets \
-                                        --template-url https://$s3_domain/$templatesbucket$templatespath/Core-S3-StandardBuckets.json \
-                                        --parameters ParameterKey=AccountAlias,ParameterValue=$AWS_ACCOUNT_NAME \
+        aws cloudformation update-stack --stack-name StandardSubscriptions \
+                                        --template-url https://$s3_domain/$templatesbucket$templatespath/Core-StandardSubscriptions.json \
                                         --profile $profile --region $region --output table
     else
-        echo "# aws cloudformation update-stack --stack-name StandardBuckets \\"
-        echo ">                                 --template-body file://$templatesdir/Core-S3-StandardBuckets.json \\"
-        echo ">                                 --parameters ParameterKey=AccountAlias,ParameterValue=$AWS_ACCOUNT_NAME \\"
+        echo "# aws cloudformation update-stack --stack-name StandardSubscriptions \\"
+        echo ">                                 --template-body file://$templatesdir/Core-StandardSubscriptions.json \\"
         echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation update-stack --stack-name StandardBuckets \
-                                        --template-body file://$templatesdir/Core-S3-StandardBuckets.json \
-                                        --parameters ParameterKey=AccountAlias,ParameterValue=$AWS_ACCOUNT_NAME \
+        aws cloudformation update-stack --stack-name StandardSubscriptions \
+                                        --template-body file://$templatesdir/Core-StandardSubscriptions.json \
                                         --profile $profile --region $region --output table
     fi
 
@@ -343,15 +337,15 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name StandardBuckets \\"
+echo "aws cloudformation describe-stacks --stack-name StandardSubscriptions \\"
 echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
 echo "                                   --profile $profile --region $region --output table"
 echo
-echo "aws cloudformation describe-stack-events --stack-name StandardBuckets --max-items 5 \\"
+echo "aws cloudformation describe-stack-events --stack-name StandardSubscriptions --max-items 5 \\"
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if [ "$(aws cloudformation describe-stacks --stack-name StandardBuckets \
+if [ "$(aws cloudformation describe-stacks --stack-name StandardSubscriptions \
                                            --query 'Stacks[].StackStatus' \
                                            --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
@@ -366,10 +360,10 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name StandardBuckets \\"
+        echo "# aws cloudformation describe-stacks --stack-name StandardSubscriptions \\"
         echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
         echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name StandardBuckets \
+        aws cloudformation describe-stacks --stack-name StandardSubscriptions \
                                            --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table 2> /dev/null
         pause
@@ -378,14 +372,14 @@ else
         seconds=$update_default
         while ((attempt++ <= update_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name StandardBuckets --max-items 5 \\"
+            echo "# aws cloudformation describe-stack-events --stack-name StandardSubscriptions --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
             echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name StandardBuckets --max-items 5 \
+            aws cloudformation describe-stack-events --stack-name StandardSubscriptions --max-items 5 \
                                                      --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
                                                      --profile $profile --region $region --output table 2> /dev/null
 
-            status=$(aws cloudformation describe-stacks --stack-name StandardBuckets \
+            status=$(aws cloudformation describe-stacks --stack-name StandardSubscriptions \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -446,7 +440,7 @@ if [ $verbose = 1 ]; then
     echo
     echo "Commands:"
     echo
-    echo "aws cloudformation describe-stack-resources --stack-name StandardBuckets \\"
+    echo "aws cloudformation describe-stack-resources --stack-name StandardSubscriptions \\"
     echo "                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
     echo "                                            --profile $profile --region $region --output table"
 
@@ -454,10 +448,10 @@ if [ $verbose = 1 ]; then
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stack-resources --stack-name StandardBuckets \\"
+        echo "# aws cloudformation describe-stack-resources --stack-name StandardSubscriptions \\"
         echo ">                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
         echo ">                                             --profile $profile --region $region --output table"
-        aws cloudformation describe-stack-resources --stack-name StandardBuckets \
+        aws cloudformation describe-stack-resources --stack-name StandardSubscriptions \
                                                     --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \
                                                     --profile $profile --region $region --output table 2> /dev/null
 
