Merge Environment and Core improvements and fixes (#11)
* Initial Environment VPC Templates and Scripts

* major restructuring of VPN templates and driver scripts, as well as changes triggered in other files

* fixed some typos

* add kmccutchen, gveazey Users

* add BillingAlarms Template and driver scripts

* fix incorrect environment tagging, missing stack input parameters

diff --git a/identity/bin/identity-create-customusers-stack b/identity/bin/identity-create-customusers-stack
--- a/identity/bin/identity-create-customusers-stack
+++ b/identity/bin/identity-create-customusers-stack
@@ -5,9 +5,9 @@
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
 #
-# Since this script is run during initial bootstrapping of an Account which 
+# Since this script is run during initial bootstrapping of an Account which
 # may not yet have certain S3 buckets created to hold templates, the
-# script checks for the existance of the S3 templates bucket, and if it 
+# script checks for the existance of the S3 templates bucket, and if it
 # exists, it will upload the template to the bucket and run it via URL,
 # but if it does not exist, it will run it via file.
 #
@@ -195,6 +195,18 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
+if ! aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Stack dependency missing - StandardManagedPolicies Stack does not exist!"
+    exit 5
+fi
+
+if ! aws cloudformation describe-stacks --stack-name StandardGroups \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Stack dependency missing - StandardGroups Stack does not exist!"
+    exit 5
+fi
+
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
 unset AWS_CREDENTIAL_FILE
@@ -294,7 +306,7 @@ if [ ! -z $templatesbucket ]; then
     echo "                                             ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
     echo "                                --tags Key=Company,Value=$COMPANY_NAME \\"
     echo "                                       Key=System,Value=$SYSTEM_NAME \\"
-    echo "                                       Key=Environment,Value=$ENVIRONMENT_NAME \\"
+    echo "                                       Key=Environment,Value=Identity \\"
     echo "                                       Key=Owner,Value=$OWNER_EMAIL \\"
     echo "                                --capabilities CAPABILITY_NAMED_IAM \\"
     echo "                                --profile $profile --region $region --output table"
@@ -306,7 +318,7 @@ else
     echo "                                             ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
     echo "                                --tags Key=Company,Value=$COMPANY_NAME \\"
     echo "                                       Key=System,Value=$SYSTEM_NAME \\"
-    echo "                                       Key=Environment,Value=$ENVIRONMENT_NAME \\"
+    echo "                                       Key=Environment,Value=Identity \\"
     echo "                                       Key=Owner,Value=$OWNER_EMAIL \\"
     echo "                                --capabilities CAPABILITY_NAMED_IAM \\"
     echo "                                --profile $profile --region $region --output table"
@@ -334,7 +346,7 @@ else
             echo ">                                              ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
             echo ">                                 --tags Key=Company,Value=$COMPANY_NAME \\"
             echo ">                                        Key=System,Value=$SYSTEM_NAME \\"
-            echo ">                                        Key=Environment,Value=$ENVIRONMENT_NAME \\"
+            echo ">                                        Key=Environment,Value=Identity \\"
             echo ">                                        Key=Owner,Value=$OWNER_EMAIL \\"
             echo ">                                 --capabilities CAPABILITY_NAMED_IAM \\"
             echo ">                                 --profile $profile --region $region --output table"
@@ -345,7 +357,7 @@ else
                                                          ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \
                                             --tags Key=Company,Value=$COMPANY_NAME \
                                                    Key=System,Value=$SYSTEM_NAME \
-                                                   Key=Environment,Value=$ENVIRONMENT_NAME \
+                                                   Key=Environment,Value=Identity \
                                                    Key=Owner,Value=$OWNER_EMAIL \
                                             --capabilities CAPABILITY_NAMED_IAM \
                                             --profile $profile --region $region --output table
@@ -357,7 +369,7 @@ else
             echo ">                                              ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
             echo ">                                 --tags Key=Company,Value=$COMPANY_NAME \\"
             echo ">                                        Key=System,Value=$SYSTEM_NAME \\"
-            echo ">                                        Key=Environment,Value=$ENVIRONMENT_NAME \\"
+            echo ">                                        Key=Environment,Value=Identity \\"
             echo ">                                        Key=Owner,Value=$OWNER_EMAIL \\"
             echo ">                                 --capabilities CAPABILITY_NAMED_IAM \\"
             echo ">                                 --profile $profile --region $region --output table"
@@ -368,7 +380,7 @@ else
                                                          ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \
                                             --tags Key=Company,Value=$COMPANY_NAME \
                                                    Key=System,Value=$SYSTEM_NAME \
-                                                   Key=Environment,Value=$ENVIRONMENT_NAME \
+                                                   Key=Environment,Value=Identity \
                                                    Key=Owner,Value=$OWNER_EMAIL \
                                             --capabilities CAPABILITY_NAMED_IAM \
                                             --profile $profile --region $region --output table
