refactor file naming convention slightly to remove Service; split out custom users

diff --git a/identity/bin/identity-create-standardusers-stack b/identity/bin/identity-create-standardusers-stack
--- a/identity/bin/identity-create-standardusers-stack
+++ b/identity/bin/identity-create-standardusers-stack
@@ -1,9 +1,15 @@
 #!/bin/bash
 #
-# This script deletes the IAM StandardUsers Stack in the Identity Account.
+# This script creates the StandardUsers Stack in the Identity Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
+#
+# Since this script is run during initial bootstrapping of an Account which 
+# may not yet have certain S3 buckets created to hold templates, the
+# script checks for the existance of the S3 templates bucket, and if it 
+# exists, it will upload the template to the bucket and run it via URL,
+# but if it does not exist, it will run it via file.
 #
 
 #  1. Initalize Environment
@@ -22,8 +28,8 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-delete_default=15
-delete_attempts=20
+create_default=15
+create_attempts=20
 
 interactive=1
 speed=100
@@ -31,6 +37,9 @@ verbose=0
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_NAME:-irops}
 user=${AWS_USER_NAME:-administrator}
+
+templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$account}
+templatespath=/identity
 
 
 #  2. Define functions
@@ -177,15 +186,13 @@ fi
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
-    echo "Could not find AWS ($account) Account Demo ($user) User AWSCLI profile!"
+    echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
     exit 53
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardUsers \
-                                        --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - StandardUsers Stack does not exist!"
-    exit 2
+if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
+    unset templatesbucket
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -198,6 +205,7 @@ unset EC2_CERT
 #  5. Run
 
 start=$(date +%s)
+
 
 ((++step))
 if [ $verbose = 1 ]; then
@@ -230,24 +238,75 @@ fi
 
 
 ((++step))
+if [ -n $templatesbucket ]; then
+    clear
+    echo
+    echo "============================================================"
+    echo
+    echo "$(printf '%2d' $step). Sync Template to ($templatesbucket) Bucket"
+    echo
+    echo "============================================================"
+    echo
+    echo "Commands:"
+    echo
+    echo "aws s3 sync $templatesdir \\"
+    echo "            s3://$templatesbucket$templatespath \\"
+    echo "            --exclude '*' --include 'Identity-StandardUsers.json' \\"
+    echo "            --profile $profile --region $region --output table"
+
+    next 50
+
+    echo
+    echo "# aws s3 sync $templatesdir \\"
+    echo ">             s3://$templatesbucket$templatespath \\"
+    echo ">             --exclude '*' --include 'Identity-StandardUsers.json' \\"
+    echo ">             --profile $profile --region $region --output table"
+    aws s3 sync $templatesdir \
+                s3://$templatesbucket$templatespath \
+                --exclude '*' --include 'Identity-StandardUsers.json' \
+                --profile $profile --region $region --output table
+
+    next 50
+fi
+
+
+((++step))
 clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Delete the Stack"
+echo "$(printf '%2d' $step). Create the Stack"
+if [ -n $templatesbucket ]; then
+    echo "    - Referencing the template as an S3 URL"
+else
+    echo "    - Referencing the template as a local File"
+fi
 echo
 echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation delete-stack --stack-name StandardUsers \\"
-echo "                                --profile $profile --region $region --output table"
+if [ -n $templatesbucket ]; then
+    echo "aws cloudformation create-stack --stack-name StandardUsers \\"
+    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-StandardUsers.json \\"
+    echo "                                --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
+    echo "                                             ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
+    echo "                                --capabilities CAPABILITY_NAMED_IAM \\"
+    echo "                                --profile $profile --region $region --output table"
+else
+    echo "aws cloudformation create-stack --stack-name StandardUsers \\"
+    echo "                                --template-body file://$templatesdir/Identity-StandardUsers.json \\"
+    echo "                                --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
+    echo "                                --parameters ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
+    echo "                                --capabilities CAPABILITY_NAMED_IAM \\"
+    echo "                                --profile $profile --region $region --output table"
+fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardUsers \
+if aws cloudformation describe-stacks --stack-name StandardUsers \
                                       --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
-    echo "Already Deleted!"
+    echo "Already Created!"
     tput sgr0
 
     next 50
@@ -257,10 +316,31 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation delete-stack --stack-name StandardUsers \\"
-        echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation delete-stack --stack-name StandardUsers \
-                                        --profile $profile --region $region --output table
+        if [ -n $templates-bucket ]; then
+            echo "# aws cloudformation create-stack --stack-name StandardUsers \\"
+            echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-StandardUsers.json \\"
+            echo ">                                 --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
+            echo ">                                              ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
+            echo ">                                 --capabilities CAPABILITY_NAMED_IAM \\"
+            echo ">                                 --profile $profile --region $region --output table"
+            aws cloudformation create-stack --stack-name StandardUsers \
+                                            --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-StandardUsers.json \
+                                            --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \
+                                                         ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \
+                                            --capabilities CAPABILITY_NAMED_IAM \
+                                            --profile $profile --region $region --output table
+        else
+            echo "# aws cloudformation create-stack --stack-name StandardUsers \\"
+            echo ">                                 --template-body file://$templatesdir/Identity-StandardUsers.json \\"
+            echo ">                                 --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
+            echo ">                                              ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
+            echo ">                                 --capabilities CAPABILITY_NAMED_IAM \\"
+            echo ">                                 --profile $profile --region $region --output table"
+            aws cloudformation create-stack --stack-name StandardUsers \
+                                            --template-body file://$templatesdir/Identity-StandardUsers.json \
+                                            --capabilities CAPABILITY_NAMED_IAM \
+                                            --profile $profile --region $region --output table
+        fi
 
         next
     fi
@@ -272,7 +352,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack deletion"
+echo "$(printf '%2d' $step). Monitor Stack creation"
 echo
 echo "============================================================"
 echo
@@ -286,11 +366,12 @@ echo "aws cloudformation describe-stack-events --stack-name StandardUsers --max-
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if ! aws cloudformation describe-stacks --stack-name StandardUsers \
-                                        --profile $profile --region $region &> /dev/null; then
+if [ "$(aws cloudformation describe-stacks --stack-name StandardUsers \
+                                           --query 'Stacks[].StackStatus' \
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
     echo
     tput rev
-    echo "Already Deleted!"
+    echo "Already Complete!"
     tput sgr0
 
     next 50
@@ -309,8 +390,8 @@ else
         pause
 
         attempt=0
-        seconds=$delete_default
-        while ((attempt++ <= delete_attempts)); do
+        seconds=$create_default
+        while ((attempt++ <= create_attempts)); do
             echo
             echo "# aws cloudformation describe-stack-events --stack-name StandardUsers --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
@@ -362,6 +443,38 @@ if [ $verbose = 1 ]; then
         echo ">                                    --profile $profile --region $region --output table"
         aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table
+
+        next
+    fi
+fi
+
+
+((++step))
+if [ $verbose = 1 ]; then
+    clear
+    echo
+    echo "============================================================"
+    echo
+    echo "$(printf '%2d' $step). List Resulting Stack Resources"
+    echo
+    echo "============================================================"
+    echo
+    echo "Commands:"
+    echo
+    echo "aws cloudformation describe-stack-resources --stack-name StandardUsers \\"
+    echo "                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
+    echo "                                            --profile $profile --region $region --output table"
+
+    run 50
+
+    if [ $choice = y ]; then
+        echo
+        echo "# aws cloudformation describe-stack-resources --stack-name StandardUsers \\"
+        echo ">                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
+        echo ">                                             --profile $profile --region $region --output table"
+        aws cloudformation describe-stack-resources --stack-name StandardUsers \
+                                                    --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \
+                                                    --profile $profile --region $region --output table 2> /dev/null
 
         next
     fi
diff --git a/identity/bin/identity-delete-customusers-stack b/identity/bin/identity-delete-customusers-stack
--- a/identity/bin/identity-delete-customusers-stack
+++ b/identity/bin/identity-delete-customusers-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script deletes the IAM StandardRoles Stack in the Identity Account.
+# This script deletes the CustomUsers Stack in the Identity Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
@@ -182,9 +182,9 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 53
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardRoles \
+if ! aws cloudformation describe-stacks --stack-name CustomUsers \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - StandardRoles Stack does not exist!"
+    echo "Unable to delete - CustomUsers Stack does not exist!"
     exit 2
 fi
 
@@ -240,10 +240,10 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation delete-stack --stack-name StandardRoles \\"
+echo "aws cloudformation delete-stack --stack-name CustomUsers \\"
 echo "                                --profile $profile --region $region --output table"
 
-if ! aws cloudformation describe-stacks --stack-name StandardRoles \
+if ! aws cloudformation describe-stacks --stack-name CustomUsers \
                                       --profile $profile --region $region --output text &> /dev/null; then
     echo
     tput rev
@@ -257,9 +257,9 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation delete-stack --stack-name StandardRoles \\"
+        echo "# aws cloudformation delete-stack --stack-name CustomUsers \\"
         echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation delete-stack --stack-name StandardRoles \
+        aws cloudformation delete-stack --stack-name CustomUsers \
                                         --profile $profile --region $region --output table
 
         next
@@ -278,15 +278,15 @@ echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name StandardRoles \\"
+echo "aws cloudformation describe-stacks --stack-name CustomUsers \\"
 echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
 echo "                                   --profile $profile --region $region --output table"
 echo
-echo "aws cloudformation describe-stack-events --stack-name StandardRoles --max-items 5 \\"
+echo "aws cloudformation describe-stack-events --stack-name CustomUsers --max-items 5 \\"
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if ! aws cloudformation describe-stacks --stack-name StandardRoles \
+if ! aws cloudformation describe-stacks --stack-name CustomUsers \
                                         --profile $profile --region $region &> /dev/null; then
     echo
     tput rev
@@ -300,10 +300,10 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name StandardRoles \\"
+        echo "# aws cloudformation describe-stacks --stack-name CustomUsers \\"
         echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
         echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name StandardRoles \
+        aws cloudformation describe-stacks --stack-name CustomUsers \
                                            --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table 2> /dev/null
         pause
@@ -312,14 +312,14 @@ else
         seconds=$delete_default
         while ((attempt++ <= delete_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name StandardRoles --max-items 5 \\"
+            echo "# aws cloudformation describe-stack-events --stack-name CustomUsers --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
             echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name StandardRoles --max-items 5 \
+            aws cloudformation describe-stack-events --stack-name CustomUsers --max-items 5 \
                                                      --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
                                                      --profile $profile --region $region --output table 2> /dev/null
 
-            status=$(aws cloudformation describe-stacks --stack-name StandardRoles \
+            status=$(aws cloudformation describe-stacks --stack-name CustomUsers \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
             if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
diff --git a/identity/bin/identity-delete-standardroles-stack b/identity/bin/identity-delete-standardroles-stack
--- a/identity/bin/identity-delete-standardroles-stack
+++ b/identity/bin/identity-delete-standardroles-stack
@@ -1,15 +1,9 @@
 #!/bin/bash
 #
-# This script updates the IAM StandardManagedPolicies Stack in the Identity Account.
+# This script deletes the StandardRoles Stack in the Identity Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
-#
-# Since this script is run during initial bootstrapping of an Account which
-# may not yet have certain S3 buckets created to hold templates, the
-# script checks for the existance of the S3 templates bucket, and if it
-# exists, it will upload the template to the bucket and run it via URL,
-# but if it does not exist, it will run it via file.
 #
 
 #  1. Initalize Environment
@@ -28,8 +22,8 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-update_default=15
-update_attempts=20
+delete_default=15
+delete_attempts=20
 
 interactive=1
 speed=100
@@ -37,9 +31,6 @@ verbose=0
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_NAME:-irops}
 user=${AWS_USER_NAME:-administrator}
-
-templatesbucket=${AWS_TEMPLATES_BUCKET:-templates-$account}
-templatespath=/identity
 
 
 #  2. Define functions
@@ -186,18 +177,14 @@ fi
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
-    echo "Could not find ($account) Account ($user) User AWSCLI profile!"
+    echo "Could not find AWS ($account) Account Demo ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
     exit 53
 fi
 
-if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
-    unset templatesbucket
-fi
-
-if ! aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
+if ! aws cloudformation describe-stacks --stack-name StandardRoles \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to update - StandardManagedPolicies Stack does not exist!"
+    echo "Unable to delete - StandardRoles Stack does not exist!"
     exit 2
 fi
 
@@ -211,7 +198,6 @@ unset EC2_CERT
 #  5. Run
 
 start=$(date +%s)
-
 
 ((++step))
 if [ $verbose = 1 ]; then
@@ -244,91 +230,40 @@ fi
 
 
 ((++step))
-if [ -n $templatesbucket ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). Sync Template to ($templatesbucket) Bucket"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "aws s3 sync $templatesdir \\"
-    echo "            s3://$templatesbucket$templatespath \\"
-    echo "            --exclude '*' --include 'Identity-IAM-StandardManagedPolicies.json' \\"
-    echo "            --profile $profile --region $region --output table"
-
-    next 50
-
-    echo
-    echo "# aws s3 sync $templatesdir \\"
-    echo ">             s3://$templatesbucket$templatespath \\"
-    echo ">             --exclude '*' --include 'Identity-IAM-StandardManagedPolicies.json' \\"
-    echo ">             --profile $profile --region $region --output table"
-    aws s3 sync $templatesdir \
-                s3://$templatesbucket$templatespath \
-                --exclude '*' --include 'Identity-IAM-StandardManagedPolicies.json' \
-                --profile $profile --region $region --output table
-
-    next 50
-fi
-
-
-((++step))
 clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Update the Stack"
-if [ -n $templatesbucket ]; then
-    echo "    - Referencing the template as an S3 URL"
-else
-    echo "    - Referencing the template as a local File"
-fi
+echo "$(printf '%2d' $step). Delete the Stack"
 echo
 echo "============================================================"
 echo
 echo "Commands:"
 echo
-if [ -n $templatesbucket ]; then
-    echo "aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
-    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-IAM-StandardManagedPolicies.json \\"
-    echo "                                --capabilities CAPABILITY_IAM \\"
-    echo "                                --profile $profile --region $region --output table"
-else
-    echo "aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
-    echo "                                --template-body file://$templatesdir/Identity-IAM-StandardManagedPolicies.json \\"
-    echo "                                --capabilities CAPABILITY_IAM \\"
-    echo "                                --profile $profile --region $region --output table"
-fi
+echo "aws cloudformation delete-stack --stack-name StandardRoles \\"
+echo "                                --profile $profile --region $region --output table"
 
-run
-
-if [ $choice = y ]; then
+if ! aws cloudformation describe-stacks --stack-name StandardRoles \
+                                      --profile $profile --region $region --output text &> /dev/null; then
     echo
-    if [ -n $templates-bucket ]; then
-        echo "# aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
-        echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-IAM-StandardManagedPolicies.json \\"
-        echo ">                                 --capabilities CAPABILITY_IAM \\"
+    tput rev
+    echo "Already Deleted!"
+    tput sgr0
+
+    next 50
+
+else
+    run
+
+    if [ $choice = y ]; then
+        echo
+        echo "# aws cloudformation delete-stack --stack-name StandardRoles \\"
         echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation update-stack --stack-name StandardManagedPolicies \
-                                        --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-IAM-StandardManagedPolicies.json \
-                                        --capabilities CAPABILITY_IAM \
+        aws cloudformation delete-stack --stack-name StandardRoles \
                                         --profile $profile --region $region --output table
-    else
-        echo "# aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
-        echo ">                                 --template-body file://$templatesdir/Identity-IAM-StandardManagedPolicies.json \\"
-        echo ">                                 --capabilities CAPABILITY_IAM \\"
-        echo ">                                 --profile $profile --region $region --output table"
-        aws cloudformation update-stack --stack-name StandardManagedPolicies \
-                                        --template-body file://$templatesdir/Identity-IAM-StandardManagedPolicies.json \
-                                        --capabilities CAPABILITY_IAM \
-                                        --profile $profile --region $region --output table
+
+        next
     fi
-
-    next
 fi
 
 
@@ -337,26 +272,25 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack update"
+echo "$(printf '%2d' $step). Monitor Stack deletion"
 echo
 echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name StandardManagedPolicies \\"
+echo "aws cloudformation describe-stacks --stack-name StandardRoles \\"
 echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
 echo "                                   --profile $profile --region $region --output table"
 echo
-echo "aws cloudformation describe-stack-events --stack-name StandardManagedPolicies --max-items 5 \\"
+echo "aws cloudformation describe-stack-events --stack-name StandardRoles --max-items 5 \\"
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if [ "$(aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
-                                           --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
+if ! aws cloudformation describe-stacks --stack-name StandardRoles \
+                                        --profile $profile --region $region &> /dev/null; then
     echo
     tput rev
-    echo "Already Complete!"
+    echo "Already Deleted!"
     tput sgr0
 
     next 50
@@ -366,29 +300,29 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name StandardManagedPolicies \\"
+        echo "# aws cloudformation describe-stacks --stack-name StandardRoles \\"
         echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
         echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
+        aws cloudformation describe-stacks --stack-name StandardRoles \
                                            --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table 2> /dev/null
         pause
 
         attempt=0
-        seconds=$update_default
-        while ((attempt++ <= update_attempts)); do
+        seconds=$delete_default
+        while ((attempt++ <= delete_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name StandardManagedPolicies --max-items 5 \\"
+            echo "# aws cloudformation describe-stack-events --stack-name StandardRoles --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
             echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name StandardManagedPolicies --max-items 5 \
+            aws cloudformation describe-stack-events --stack-name StandardRoles --max-items 5 \
                                                      --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
                                                      --profile $profile --region $region --output table 2> /dev/null
 
-            status=$(aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
+            status=$(aws cloudformation describe-stacks --stack-name StandardRoles \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -428,38 +362,6 @@ if [ $verbose = 1 ]; then
         echo ">                                    --profile $profile --region $region --output table"
         aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table
-
-        next
-    fi
-fi
-
-
-((++step))
-if [ $verbose = 1 ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). List Resulting Stack Resources"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "aws cloudformation describe-stack-resources --stack-name StandardManagedPolicies \\"
-    echo "                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
-    echo "                                            --profile $profile --region $region --output table"
-
-    run 50
-
-    if [ $choice = y ]; then
-        echo
-        echo "# aws cloudformation describe-stack-resources --stack-name StandardManagedPolicies \\"
-        echo ">                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
-        echo ">                                             --profile $profile --region $region --output table"
-        aws cloudformation describe-stack-resources --stack-name StandardManagedPolicies \
-                                                    --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \
-                                                    --profile $profile --region $region --output table 2> /dev/null
 
         next
     fi
diff --git a/identity/bin/identity-update-standardmanagedpolicies-stack b/identity/bin/identity-update-standardmanagedpolicies-stack
--- a/identity/bin/identity-update-standardmanagedpolicies-stack
+++ b/identity/bin/identity-update-standardmanagedpolicies-stack
@@ -1,13 +1,13 @@
 #!/bin/bash
 #
-# This script creates the IAM StandardUsers Stack in the Identity Account.
+# This script updates the StandardManagedPolicies Stack in the Identity Account.
 #
 # This script is written in a format suitable for interactive demos,
 # but can be run non-Iteractively and more quickly with the "-I" flag.
 #
-# Since this script is run during initial bootstrapping of an Account which 
+# Since this script is run during initial bootstrapping of an Account which
 # may not yet have certain S3 buckets created to hold templates, the
-# script checks for the existance of the S3 templates bucket, and if it 
+# script checks for the existance of the S3 templates bucket, and if it
 # exists, it will upload the template to the bucket and run it via URL,
 # but if it does not exist, it will run it via file.
 #
@@ -28,8 +28,8 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-create_default=15
-create_attempts=20
+update_default=15
+update_attempts=20
 
 interactive=1
 speed=100
@@ -195,6 +195,12 @@ if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region
     unset templatesbucket
 fi
 
+if ! aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo "Unable to update - StandardManagedPolicies Stack does not exist!"
+    exit 2
+fi
+
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
 unset AWS_CREDENTIAL_FILE
@@ -251,7 +257,7 @@ if [ -n $templatesbucket ]; then
     echo
     echo "aws s3 sync $templatesdir \\"
     echo "            s3://$templatesbucket$templatespath \\"
-    echo "            --exclude '*' --include 'Identity-IAM-StandardUsers.json' \\"
+    echo "            --exclude '*' --include 'Identity-StandardManagedPolicies.json' \\"
     echo "            --profile $profile --region $region --output table"
 
     next 50
@@ -259,11 +265,11 @@ if [ -n $templatesbucket ]; then
     echo
     echo "# aws s3 sync $templatesdir \\"
     echo ">             s3://$templatesbucket$templatespath \\"
-    echo ">             --exclude '*' --include 'Identity-IAM-StandardUsers.json' \\"
+    echo ">             --exclude '*' --include 'Identity-StandardManagedPolicies.json' \\"
     echo ">             --profile $profile --region $region --output table"
     aws s3 sync $templatesdir \
                 s3://$templatesbucket$templatespath \
-                --exclude '*' --include 'Identity-IAM-StandardUsers.json' \
+                --exclude '*' --include 'Identity-StandardManagedPolicies.json' \
                 --profile $profile --region $region --output table
 
     next 50
@@ -275,7 +281,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Create the Stack"
+echo "$(printf '%2d' $step). Update the Stack"
 if [ -n $templatesbucket ]; then
     echo "    - Referencing the template as an S3 URL"
 else
@@ -287,63 +293,42 @@ echo
 echo "Commands:"
 echo
 if [ -n $templatesbucket ]; then
-    echo "aws cloudformation create-stack --stack-name StandardUsers \\"
-    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-IAM-StandardUsers.json \\"
-    echo "                                --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
-    echo "                                             ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
-    echo "                                --capabilities CAPABILITY_NAMED_IAM \\"
+    echo "aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
+    echo "                                --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-StandardManagedPolicies.json \\"
+    echo "                                --capabilities CAPABILITY_IAM \\"
     echo "                                --profile $profile --region $region --output table"
 else
-    echo "aws cloudformation create-stack --stack-name StandardUsers \\"
-    echo "                                --template-body file://$templatesdir/Identity-IAM-StandardUsers.json \\"
-    echo "                                --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
-    echo "                                --parameters ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
-    echo "                                --capabilities CAPABILITY_NAMED_IAM \\"
+    echo "aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
+    echo "                                --template-body file://$templatesdir/Identity-StandardManagedPolicies.json \\"
+    echo "                                --capabilities CAPABILITY_IAM \\"
     echo "                                --profile $profile --region $region --output table"
 fi
 
-if aws cloudformation describe-stacks --stack-name StandardUsers \
-                                      --profile $profile --region $region --output text &> /dev/null; then
+run
+
+if [ $choice = y ]; then
     echo
-    tput rev
-    echo "Already Created!"
-    tput sgr0
-
-    next 50
-
-else
-    run
-
-    if [ $choice = y ]; then
-        echo
-        if [ -n $templates-bucket ]; then
-            echo "# aws cloudformation create-stack --stack-name StandardUsers \\"
-            echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-IAM-StandardUsers.json \\"
-            echo ">                                 --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
-            echo ">                                              ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
-            echo ">                                 --capabilities CAPABILITY_NAMED_IAM \\"
-            echo ">                                 --profile $profile --region $region --output table"
-            aws cloudformation create-stack --stack-name StandardUsers \
-                                            --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-IAM-StandardUsers.json \
-                                            --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \
-                                                         ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \
-                                            --capabilities CAPABILITY_NAMED_IAM \
-                                            --profile $profile --region $region --output table
-        else
-            echo "# aws cloudformation create-stack --stack-name StandardUsers \\"
-            echo ">                                 --template-body file://$templatesdir/Identity-IAM-StandardUsers.json \\"
-            echo ">                                 --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\"
-            echo ">                                              ParameterKey=StandardGroupsStackName,ParameterValue=StandardGroups \\"
-            echo ">                                 --capabilities CAPABILITY_NAMED_IAM \\"
-            echo ">                                 --profile $profile --region $region --output table"
-            aws cloudformation create-stack --stack-name StandardUsers \
-                                            --template-body file://$templatesdir/Identity-IAM-StandardUsers.json \
-                                            --capabilities CAPABILITY_NAMED_IAM \
-                                            --profile $profile --region $region --output table
-        fi
-
-        next
+    if [ -n $templates-bucket ]; then
+        echo "# aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
+        echo ">                                 --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-StandardManagedPolicies.json \\"
+        echo ">                                 --capabilities CAPABILITY_IAM \\"
+        echo ">                                 --profile $profile --region $region --output table"
+        aws cloudformation update-stack --stack-name StandardManagedPolicies \
+                                        --template-url https://$s3_domain/$templatesbucket$templatespath/Identity-StandardManagedPolicies.json \
+                                        --capabilities CAPABILITY_IAM \
+                                        --profile $profile --region $region --output table
+    else
+        echo "# aws cloudformation update-stack --stack-name StandardManagedPolicies \\"
+        echo ">                                 --template-body file://$templatesdir/Identity-StandardManagedPolicies.json \\"
+        echo ">                                 --capabilities CAPABILITY_IAM \\"
+        echo ">                                 --profile $profile --region $region --output table"
+        aws cloudformation update-stack --stack-name StandardManagedPolicies \
+                                        --template-body file://$templatesdir/Identity-StandardManagedPolicies.json \
+                                        --capabilities CAPABILITY_IAM \
+                                        --profile $profile --region $region --output table
     fi
+
+    next
 fi
 
 
@@ -352,23 +337,23 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Monitor Stack creation"
+echo "$(printf '%2d' $step). Monitor Stack update"
 echo
 echo "============================================================"
 echo
 echo "Commands:"
 echo
-echo "aws cloudformation describe-stacks --stack-name StandardUsers \\"
+echo "aws cloudformation describe-stacks --stack-name StandardManagedPolicies \\"
 echo "                                   --query 'Stacks[].[StackName,StackStatus]' \\"
 echo "                                   --profile $profile --region $region --output table"
 echo
-echo "aws cloudformation describe-stack-events --stack-name StandardUsers --max-items 5 \\"
+echo "aws cloudformation describe-stack-events --stack-name StandardManagedPolicies --max-items 5 \\"
 echo "                                         --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
 echo "                                         --profile $profile --region $region --output table"
 
-if [ "$(aws cloudformation describe-stacks --stack-name StandardUsers \
+if [ "$(aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
                                            --query 'Stacks[].StackStatus' \
-                                           --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
+                                           --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
     echo
     tput rev
     echo "Already Complete!"
@@ -381,29 +366,29 @@ else
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stacks --stack-name StandardUsers \\"
+        echo "# aws cloudformation describe-stacks --stack-name StandardManagedPolicies \\"
         echo ">                                    --query 'Stacks[].[StackName,StackStatus]' \\"
         echo ">                                    --profile $profile --region $region --output table"
-        aws cloudformation describe-stacks --stack-name StandardUsers \
+        aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
                                            --query 'Stacks[].[StackName,StackStatus]' \
                                            --profile $profile --region $region --output table 2> /dev/null
         pause
 
         attempt=0
-        seconds=$create_default
-        while ((attempt++ <= create_attempts)); do
+        seconds=$update_default
+        while ((attempt++ <= update_attempts)); do
             echo
-            echo "# aws cloudformation describe-stack-events --stack-name StandardUsers --max-items 5 \\"
+            echo "# aws cloudformation describe-stack-events --stack-name StandardManagedPolicies --max-items 5 \\"
             echo ">                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\"
             echo ">                                          --profile $profile --region $region --output table"
-            aws cloudformation describe-stack-events --stack-name StandardUsers --max-items 5 \
+            aws cloudformation describe-stack-events --stack-name StandardManagedPolicies --max-items 5 \
                                                      --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \
                                                      --profile $profile --region $region --output table 2> /dev/null
 
-            status=$(aws cloudformation describe-stacks --stack-name StandardUsers \
+            status=$(aws cloudformation describe-stacks --stack-name StandardManagedPolicies \
                                                         --query 'Stacks[].StackStatus' \
                                                         --profile $profile --region $region --output text 2> /dev/null)
-            if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+            if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                 break
             else
                 echo
@@ -461,7 +446,7 @@ if [ $verbose = 1 ]; then
     echo
     echo "Commands:"
     echo
-    echo "aws cloudformation describe-stack-resources --stack-name StandardUsers \\"
+    echo "aws cloudformation describe-stack-resources --stack-name StandardManagedPolicies \\"
     echo "                                            --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
     echo "                                            --profile $profile --region $region --output table"
 
@@ -469,10 +454,10 @@ if [ $verbose = 1 ]; then
 
     if [ $choice = y ]; then
         echo
-        echo "# aws cloudformation describe-stack-resources --stack-name StandardUsers \\"
+        echo "# aws cloudformation describe-stack-resources --stack-name StandardManagedPolicies \\"
         echo ">                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\"
         echo ">                                             --profile $profile --region $region --output table"
-        aws cloudformation describe-stack-resources --stack-name StandardUsers \
+        aws cloudformation describe-stack-resources --stack-name StandardManagedPolicies \
                                                     --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \
                                                     --profile $profile --region $region --output table 2> /dev/null
 
