changes to parameters; added missing parameter validation

diff --git a/example/bin/example-delete-webserver-stack b/example/bin/example-delete-webserver-stack
--- a/example/bin/example-delete-webserver-stack
+++ b/example/bin/example-delete-webserver-stack
@@ -153,10 +153,22 @@ shift $(($OPTIND - 1))
 
 #  4. Validate environment
 
+if [ -z $environment ]; then
+    echo "-E environment missing!"
+    echo "Could not automatically determine environment, and it was not specified as a parameter"
+    exit 16
+fi
+
+if [ -z $application ]; then
+    echo "-A application missing!"
+    echo "Could not automatically determine application, and it was not specified as a parameter"
+    exit 20
+fi
+
 if [ -z $region ]; then
     echo "-r region missing!"
     echo "Could not automatically determine region, and it was not specified as a parameter"
-    exit 20
+    exit 50
 else
     case $region in
       us-east-1)
@@ -165,20 +177,20 @@ else
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
-        exit 21;;
+        exit 51;;
     esac
 fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
     echo "Could not automatically determine account, and it was not specified as a parameter"
-    exit 22
+    exit 52
 fi
 
 if [ -z $user ]; then
     echo "-u user missing!"
     echo "Could not automatically determine user, and it was not specified as a parameter"
-    exit 24
+    exit 54
 fi
 
 profile=$account-$user
@@ -186,13 +198,13 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 53
+    exit 60
 fi
 
-if ! aws cloudformation describe-stacks --stack-name Build-NetworkAcls \
+if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
-    echo "Unable to delete - Build-NetworkAcls Stack does not exist!"
-    exit 2
+    echo "Unable to delete - $environment-$application Stack does not exist!"
+    exit 70
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -212,7 +224,7 @@ aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ $verbose = 1 ]; then
     clear
@@ -361,7 +373,7 @@ aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ $verbose = 1 ]; then
     clear
diff --git a/example/bin/example-update-webserver-stack b/example/bin/example-update-webserver-stack
--- a/example/bin/example-update-webserver-stack
+++ b/example/bin/example-update-webserver-stack
@@ -28,13 +28,13 @@ update_attempts=20
 interactive=1
 speed=100
 verbose=0
+owner=${OWNER_EMAIL:-$USER@hpe.com}
 company=${COMPANY_NAME:-Demo}
 system=${SYSTEM_NAME:-IROPS}
 environment=${ENVIRONMENT_NAME:-Production}
-owner=${OWNER_EMAIL:-$USER@hpe.com}
+environment_domain=${ENVIRONMENT_DOMAIN:-demo.iropshub.com}
 application=${APPLICATION_NAME:-WebServer}
 application_version=${APPLICATION_VERSION:-1.0.0}
-application_domain=${APPLICATION_DOMAIN:-demo.iropshub.com}
 key=${AWS_KEY_NAME:-demo}
 network=${ADMINISTRATOR_NETWORK:-0.0.0.0/0}
 region=${AWS_DEFAULT_REGION:-us-west-2}
@@ -49,24 +49,25 @@ templatespath=/core
 
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [-I [-s | -f]] [-v]"
-    echo "                  [-C company ] [-S system] [-E environment] [-O owner]"
-    echo "                  [-A application ] [-V version] [-D domain]"
-    echo "                  [-K key] [-N network ]"
+    echo "                  [-O owner] [-C company ] [-S system]"
+    echo "                  [-E environment] [-D domain]"
+    echo "                  [-A application ] [-V version]"
+    echo "                  [-k key] [-n network ]"
     echo "                  [-r region ] [-a account] [-u user]"
     echo "  -I              non-interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
+    echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
     echo "  -L location     Location Name (default: $location)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -O owner        Owner Email (default: $owner)"
+    echo "  -D domain       Environment Domain (default: $environment_domain)"
     echo "  -A application  Application Name (default: $application)"
     echo "  -V version      Application Version (default: $application_version)"
-    echo "  -D domain       Application Domain (default: $application_domain)"
-    echo "  -K key          Key (default: $key)"
-    echo "  -N network      Administrator Network (default: $network)"
+    echo "  -k key          Key (default: $key)"
+    echo "  -n network      Administrator Network (default: $network)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -152,22 +153,22 @@ next() {
 
 #  3. Parse command line options
 
-while getopts IsfvC:L:S:E:O:A:V:D:K:N:r:a:u:? arg; do
+while getopts IsfvO:C:L:S:E:D:A:V:k:n:r:a:u:? arg; do
     case $arg in
     I)  interactive=0;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
+    O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     L)  location="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    O)  owner="$OPTARG";;
+    D)  environment_domain="$OPTARG";;
     A)  application="$OPTARG";;
     V)  application_version="$OPTARG";;
-    D)  application_domain="$OPTARG";;
-    K)  key="$OPTARG";;
-    N)  network="$OPTARG";;
+    k)  key="$OPTARG";;
+    n)  network="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -181,10 +182,64 @@ shift $(($OPTIND - 1))
 
 #  4. Validate environment
 
+if [ -z $owner ]; then
+    echo "-O owner missing!"
+    echo "Could not automatically determine owner, and it was not specified as a parameter"
+    exit 10
+fi
+
+if [ -z $company ]; then
+    echo "-C company missing!"
+    echo "Could not automatically determine company, and it was not specified as a parameter"
+    exit 12
+fi
+
+if [ -z $system ]; then
+    echo "-S system missing!"
+    echo "Could not automatically determine system, and it was not specified as a parameter"
+    exit 14
+fi
+
+if [ -z $environment ]; then
+    echo "-E environment missing!"
+    echo "Could not automatically determine environment, and it was not specified as a parameter"
+    exit 16
+fi
+
+if [ -z $environment_domain ]; then
+    echo "-D domain missing!"
+    echo "Could not automatically determine domain, and it was not specified as a parameter"
+    exit 18
+fi
+
+if [ -z $application ]; then
+    echo "-A application missing!"
+    echo "Could not automatically determine application, and it was not specified as a parameter"
+    exit 20
+fi
+
+if [ -z $application_version ]; then
+    echo "-V version missing!"
+    echo "Could not automatically determine version, and it was not specified as a parameter"
+    exit 22
+fi
+
+if [ -z $key ]; then
+    echo "-K key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 30
+fi
+
+if [ -z $network ]; then
+    echo "-N network missing!"
+    echo "Could not automatically determine network, and it was not specified as a parameter"
+    exit 32
+fi
+
 if [ -z $region ]; then
     echo "-r region missing!"
     echo "Could not automatically determine region, and it was not specified as a parameter"
-    exit 20
+    exit 50
 else
     case $region in
       us-east-1)
@@ -193,20 +248,20 @@ else
         s3_domain=s3-$region.amazonaws.com;;
     *)
         echo "-r $region invalid: Please specify a valid region"
-        exit 21;;
+        exit 51;;
     esac
 fi
 
 if [ -z $account ]; then
     echo "-a account missing!"
     echo "Could not automatically determine account, and it was not specified as a parameter"
-    exit 22
+    exit 52
 fi
 
 if [ -z $user ]; then
     echo "-u user missing!"
     echo "Could not automatically determine user, and it was not specified as a parameter"
-    exit 24
+    exit 54
 fi
 
 profile=$account-$user
@@ -214,7 +269,7 @@ profile=$account-$user
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     echo "Could not find ($account) Account ($user) User AWSCLI profile!"
     echo "Expected to find: [profile $profile] in ~/.aws/config"
-    exit 53
+    exit 60
 fi
 
 if ! aws s3api head-bucket --bucket $templatesbucket --profile $profile --region $region 2> /dev/null; then
@@ -224,13 +279,13 @@ fi
 if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - $environment-VPC Stack does not exist!"
-    exit 2
+    exit 70
 fi
 
 if ! aws cloudformation describe-stacks --stack-name $environment-$application \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo "Unable to update - $environment-$application Stack does not exist!"
-    exit 3
+    exit 71
 fi
 
 # Prevent certain environment variables from breaking commands
@@ -251,7 +306,7 @@ aws cloudformation describe-stacks --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ $verbose = 1 ]; then
     clear
@@ -286,7 +341,7 @@ aws s3 sync $templatesdir \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
-eval_statement="${statement//\\$'\n'} 2> /dev/null"
+eval_statement="${statement//\\$'\n'}"
 
 if [ ! -z $templatesbucket ]; then
     clear
@@ -327,15 +382,15 @@ aws cloudformation update-stack --stack-name $environment-$application \\
                                              ParameterKey=CompanyName,ParameterValue=$company \\
                                              ParameterKey=SystemName,ParameterValue=$system \\
                                              ParameterKey=EnvironmentName,ParameterValue=$environment \\
+                                             ParameterKey=EnvironmentDomain,ParameterValue=$environment_domain \\
                                              ParameterKey=ApplicationName,ParameterValue=$application \\
                                              ParameterKey=ApplicationVersion,ParameterValue=$application_version \\
-                                             ParameterKey=ApplicationDomain,ParameterValue=$application_domain \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
                                              ParameterKey=AdministratorNetwork,ParameterValue=$network \\
-                                --tags Key=Company,Value=$company \\
+                                --tags Key=Owner,Value=$owner \\
+                                       Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
                                        Key=Environment,Value=$environment \\
-                                       Key=Owner,Value=$owner \\
                                 --capabilities CAPABILITY_IAM \\
                                 --profile $profile --region $region --output table
 EOS
@@ -476,7 +531,7 @@ fi
 read -r -d '' statement << EOS
 aws cloudformation describe-stack-resources --stack-name $environment-$application \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
-                                            --profile $profile --region $region --output table 2> /dev/null
+                                            --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
